- name: Install K3s
  shell: curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s

- name: Ensure /usr/local/bin is in PATH
  shell: echo $PATH
  register: path_check

- name: Wait for Kubernetes to be ready
  shell: /usr/local/bin/k3s kubectl get nodes
  register: result
  until: result.rc == 0
  retries: 10
  delay: 5
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

- name: Create manifests directory
  file:
    path: /var/lib/pgsql/manifests
    state: directory
    mode: '0755'

- name: Render PostgreSQL deployment manifest from template
  template:
    src: postgres-deployment.yml.j2
    dest: /var/lib/pgsql/manifests/postgres-deployment.yml
    mode: '0644'

- name: Deploy PostgreSQL on Kubernetes
  shell: /usr/local/bin/k3s kubectl apply -f /var/lib/pgsql/manifests/postgres-deployment.yml
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

